version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: "asdQWE123."
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: "always"
    networks:
      - graylog

networks:
  graylog:
    driver: "bridge"

volumes:
  postgres-data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /mnt/wwwdata/postgres-data
    #   o: bind