BEGIN;
TRUNCATE "Countires";
INSERT INTO "Countires" (id, name) VALUES (1, 'Afghanistan');
INSERT INTO "Countires" (id, name) VALUES (2, 'Albania');
INSERT INTO "Countires" (id, name) VALUES (3, 'Algeria');
INSERT INTO "Countires" (id, name) VALUES (4, 'Andorra');
INSERT INTO "Countires" (id, name) VALUES (5, 'Angola');
INSERT INTO "Countires" (id, name) VALUES (6, 'Antigua and Barbuda');
INSERT INTO "Countires" (id, name) VALUES (7, 'Argentina');
INSERT INTO "Countires" (id, name) VALUES (8, 'Armenia');
INSERT INTO "Countires" (id, name) VALUES (9, 'Australia');
INSERT INTO "Countires" (id, name) VALUES (10, 'Austria');
INSERT INTO "Countires" (id, name) VALUES (11, 'Azerbaijan');
INSERT INTO "Countires" (id, name) VALUES (12, 'Bahamas, The');
INSERT INTO "Countires" (id, name) VALUES (13, 'Bahrain');
INSERT INTO "Countires" (id, name) VALUES (14, 'Bangladesh');
INSERT INTO "Countires" (id, name) VALUES (15, 'Barbados');
INSERT INTO "Countires" (id, name) VALUES (16, 'Belarus');
INSERT INTO "Countires" (id, name) VALUES (17, 'Belgium');
INSERT INTO "Countires" (id, name) VALUES (18, 'Belize');
INSERT INTO "Countires" (id, name) VALUES (19, 'Benin (Dahomey)');
INSERT INTO "Countires" (id, name) VALUES (20, 'Bolivia');
INSERT INTO "Countires" (id, name) VALUES (21, 'Bosnia and Herzegovina');
INSERT INTO "Countires" (id, name) VALUES (22, 'Botswana');
INSERT INTO "Countires" (id, name) VALUES (23, 'Brazil');
INSERT INTO "Countires" (id, name) VALUES (24, 'Brunei');
INSERT INTO "Countires" (id, name) VALUES (25, 'Bulgaria');
INSERT INTO "Countires" (id, name) VALUES (26, 'Burkina Faso (Upper Volta)');
INSERT INTO "Countires" (id, name) VALUES (27, 'Burma');
INSERT INTO "Countires" (id, name) VALUES (28, 'Burundi');
INSERT INTO "Countires" (id, name) VALUES (29, 'Cabo Verde');
INSERT INTO "Countires" (id, name) VALUES (30, 'Cambodia');
INSERT INTO "Countires" (id, name) VALUES (31, 'Cameroon');
INSERT INTO "Countires" (id, name) VALUES (32, 'Canada');
INSERT INTO "Countires" (id, name) VALUES (33, 'Cayman Islands, The');
INSERT INTO "Countires" (id, name) VALUES (34, 'Central African Republic');
INSERT INTO "Countires" (id, name) VALUES (35, 'Chad');
INSERT INTO "Countires" (id, name) VALUES (36, 'Chile');
INSERT INTO "Countires" (id, name) VALUES (37, 'China');
INSERT INTO "Countires" (id, name) VALUES (38, 'Colombia');
INSERT INTO "Countires" (id, name) VALUES (39, 'Comoros');
INSERT INTO "Countires" (id, name) VALUES (40, 'Cook Islands');
INSERT INTO "Countires" (id, name) VALUES (41, 'Costa Rica');
INSERT INTO "Countires" (id, name) VALUES (42, 'Cote d’Ivoire (Ivory Coast)');
INSERT INTO "Countires" (id, name) VALUES (43, 'Croatia');
INSERT INTO "Countires" (id, name) VALUES (44, 'Cuba');
INSERT INTO "Countires" (id, name) VALUES (45, 'Cyprus');
INSERT INTO "Countires" (id, name) VALUES (46, 'Czechia');
INSERT INTO "Countires" (id, name) VALUES (47, 'Democratic Republic of the Congo');
INSERT INTO "Countires" (id, name) VALUES (48, 'Denmark');
INSERT INTO "Countires" (id, name) VALUES (49, 'Djibouti');
INSERT INTO "Countires" (id, name) VALUES (50, 'Dominica');
INSERT INTO "Countires" (id, name) VALUES (51, 'Dominican Republic');
INSERT INTO "Countires" (id, name) VALUES (52, 'Ecuador');
INSERT INTO "Countires" (id, name) VALUES (53, 'Egypt');
INSERT INTO "Countires" (id, name) VALUES (54, 'El Salvador');
INSERT INTO "Countires" (id, name) VALUES (55, 'Equatorial Guinea');
INSERT INTO "Countires" (id, name) VALUES (56, 'Eritrea');
INSERT INTO "Countires" (id, name) VALUES (57, 'Estonia');
INSERT INTO "Countires" (id, name) VALUES (58, 'Eswatini');
INSERT INTO "Countires" (id, name) VALUES (59, 'Ethiopia');
INSERT INTO "Countires" (id, name) VALUES (60, 'Fiji');
INSERT INTO "Countires" (id, name) VALUES (61, 'Finland');
INSERT INTO "Countires" (id, name) VALUES (62, 'France');
INSERT INTO "Countires" (id, name) VALUES (63, 'Gabon');
INSERT INTO "Countires" (id, name) VALUES (64, 'Gambia, The');
INSERT INTO "Countires" (id, name) VALUES (65, 'Georgia');
INSERT INTO "Countires" (id, name) VALUES (66, 'Germany');
INSERT INTO "Countires" (id, name) VALUES (67, 'Ghana');
INSERT INTO "Countires" (id, name) VALUES (68, 'Greece');
INSERT INTO "Countires" (id, name) VALUES (69, 'Grenada');
INSERT INTO "Countires" (id, name) VALUES (70, 'Guatemala');
INSERT INTO "Countires" (id, name) VALUES (71, 'Guinea');
INSERT INTO "Countires" (id, name) VALUES (72, 'Guinea-Bissau');
INSERT INTO "Countires" (id, name) VALUES (73, 'Guyana');
INSERT INTO "Countires" (id, name) VALUES (74, 'Haiti');
INSERT INTO "Countires" (id, name) VALUES (75, 'Holy See');
INSERT INTO "Countires" (id, name) VALUES (76, 'Honduras');
INSERT INTO "Countires" (id, name) VALUES (77, 'Hungary');
INSERT INTO "Countires" (id, name) VALUES (78, 'Iceland');
INSERT INTO "Countires" (id, name) VALUES (79, 'India');
INSERT INTO "Countires" (id, name) VALUES (80, 'Indonesia');
INSERT INTO "Countires" (id, name) VALUES (81, 'Iran');
INSERT INTO "Countires" (id, name) VALUES (82, 'Iraq');
INSERT INTO "Countires" (id, name) VALUES (83, 'Ireland');
INSERT INTO "Countires" (id, name) VALUES (84, 'Israel');
INSERT INTO "Countires" (id, name) VALUES (85, 'Italy');
INSERT INTO "Countires" (id, name) VALUES (86, 'Jamaica');
INSERT INTO "Countires" (id, name) VALUES (87, 'Japan');
INSERT INTO "Countires" (id, name) VALUES (88, 'Jordan');
INSERT INTO "Countires" (id, name) VALUES (89, 'Kazakhstan');
INSERT INTO "Countires" (id, name) VALUES (90, 'Kenya');
INSERT INTO "Countires" (id, name) VALUES (91, 'Kiribati');
INSERT INTO "Countires" (id, name) VALUES (92, 'Korea');
INSERT INTO "Countires" (id, name) VALUES (93, 'Kosovo');
INSERT INTO "Countires" (id, name) VALUES (94, 'Kuwait');
INSERT INTO "Countires" (id, name) VALUES (95, 'Kyrgyzstan');
INSERT INTO "Countires" (id, name) VALUES (96, 'Laos');
INSERT INTO "Countires" (id, name) VALUES (97, 'Latvia');
INSERT INTO "Countires" (id, name) VALUES (98, 'Lebanon');
INSERT INTO "Countires" (id, name) VALUES (99, 'Lesotho');
INSERT INTO "Countires" (id, name) VALUES (100, 'Liberia');
INSERT INTO "Countires" (id, name) VALUES (101, 'Libya');
INSERT INTO "Countires" (id, name) VALUES (102, 'Liechtenstein');
INSERT INTO "Countires" (id, name) VALUES (103, 'Lithuania');
INSERT INTO "Countires" (id, name) VALUES (104, 'Luxembourg');
INSERT INTO "Countires" (id, name) VALUES (105, 'Madagascar');
INSERT INTO "Countires" (id, name) VALUES (106, 'Malawi');
INSERT INTO "Countires" (id, name) VALUES (107, 'Malaysia');
INSERT INTO "Countires" (id, name) VALUES (108, 'Maldives');
INSERT INTO "Countires" (id, name) VALUES (109, 'Mali');
INSERT INTO "Countires" (id, name) VALUES (110, 'Malta');
INSERT INTO "Countires" (id, name) VALUES (111, 'Marshall Islands');
INSERT INTO "Countires" (id, name) VALUES (112, 'Mauritania');
INSERT INTO "Countires" (id, name) VALUES (113, 'Mauritius');
INSERT INTO "Countires" (id, name) VALUES (114, 'Mexico');
INSERT INTO "Countires" (id, name) VALUES (115, 'Micronesia');
INSERT INTO "Countires" (id, name) VALUES (116, 'Moldova');
INSERT INTO "Countires" (id, name) VALUES (117, 'Monaco');
INSERT INTO "Countires" (id, name) VALUES (118, 'Mongolia');
INSERT INTO "Countires" (id, name) VALUES (119, 'Montenegro');
INSERT INTO "Countires" (id, name) VALUES (120, 'Morocco');
INSERT INTO "Countires" (id, name) VALUES (121, 'Mozambique');
INSERT INTO "Countires" (id, name) VALUES (122, 'Namibia');
INSERT INTO "Countires" (id, name) VALUES (123, 'Nauru');
INSERT INTO "Countires" (id, name) VALUES (124, 'Nepal');
INSERT INTO "Countires" (id, name) VALUES (125, 'Netherlands, The');
INSERT INTO "Countires" (id, name) VALUES (126, 'New Zealand');
INSERT INTO "Countires" (id, name) VALUES (127, 'Nicaragua');
INSERT INTO "Countires" (id, name) VALUES (128, 'Niger');
INSERT INTO "Countires" (id, name) VALUES (129, 'Nigeria');
INSERT INTO "Countires" (id, name) VALUES (130, 'Niue');
INSERT INTO "Countires" (id, name) VALUES (131, 'North Macedonia');
INSERT INTO "Countires" (id, name) VALUES (132, 'Norway');
INSERT INTO "Countires" (id, name) VALUES (133, 'Oman');
INSERT INTO "Countires" (id, name) VALUES (134, 'Pakistan');
INSERT INTO "Countires" (id, name) VALUES (135, 'Palau');
INSERT INTO "Countires" (id, name) VALUES (136, 'Panama');
INSERT INTO "Countires" (id, name) VALUES (137, 'Papua New Guinea');
INSERT INTO "Countires" (id, name) VALUES (138, 'Paraguay');
INSERT INTO "Countires" (id, name) VALUES (139, 'Peru');
INSERT INTO "Countires" (id, name) VALUES (140, 'Philippines');
INSERT INTO "Countires" (id, name) VALUES (141, 'Poland');
INSERT INTO "Countires" (id, name) VALUES (142, 'Portugal');
INSERT INTO "Countires" (id, name) VALUES (143, 'Qatar');
INSERT INTO "Countires" (id, name) VALUES (144, 'Republic of Korea (South Korea)');
INSERT INTO "Countires" (id, name) VALUES (145, 'Republic of the Congo');
INSERT INTO "Countires" (id, name) VALUES (146, 'Romania');
INSERT INTO "Countires" (id, name) VALUES (147, 'Russia');
INSERT INTO "Countires" (id, name) VALUES (148, 'Rwanda');
INSERT INTO "Countires" (id, name) VALUES (149, 'Saint Kitts and Nevis');
INSERT INTO "Countires" (id, name) VALUES (150, 'Saint Lucia');
INSERT INTO "Countires" (id, name) VALUES (151, 'Saint Vincent and the Grenadines');
INSERT INTO "Countires" (id, name) VALUES (152, 'Samoa');
INSERT INTO "Countires" (id, name) VALUES (153, 'San Marino');
INSERT INTO "Countires" (id, name) VALUES (154, 'Sao Tome and Principe');
INSERT INTO "Countires" (id, name) VALUES (155, 'Saudi Arabia');
INSERT INTO "Countires" (id, name) VALUES (156, 'Senegal');
INSERT INTO "Countires" (id, name) VALUES (157, 'Serbia');
INSERT INTO "Countires" (id, name) VALUES (158, 'Seychelles');
INSERT INTO "Countires" (id, name) VALUES (159, 'Sierra Leone');
INSERT INTO "Countires" (id, name) VALUES (160, 'Singapore');
INSERT INTO "Countires" (id, name) VALUES (161, 'Slovakia');
INSERT INTO "Countires" (id, name) VALUES (162, 'Slovenia');
INSERT INTO "Countires" (id, name) VALUES (163, 'Solomon Islands, The');
INSERT INTO "Countires" (id, name) VALUES (164, 'Somalia');
INSERT INTO "Countires" (id, name) VALUES (165, 'South Africa');
INSERT INTO "Countires" (id, name) VALUES (166, 'South Sudan');
INSERT INTO "Countires" (id, name) VALUES (167, 'Spain');
INSERT INTO "Countires" (id, name) VALUES (168, 'Sri Lanka');
INSERT INTO "Countires" (id, name) VALUES (169, 'Sudan');
INSERT INTO "Countires" (id, name) VALUES (170, 'Suriname');
INSERT INTO "Countires" (id, name) VALUES (171, 'Sweden');
INSERT INTO "Countires" (id, name) VALUES (172, 'Switzerland');
INSERT INTO "Countires" (id, name) VALUES (173, 'Syria');
INSERT INTO "Countires" (id, name) VALUES (174, 'Tajikistan');
INSERT INTO "Countires" (id, name) VALUES (175, 'Tanzania');
INSERT INTO "Countires" (id, name) VALUES (176, 'Thailand');
INSERT INTO "Countires" (id, name) VALUES (177, 'Timor-Leste');
INSERT INTO "Countires" (id, name) VALUES (178, 'Togo');
INSERT INTO "Countires" (id, name) VALUES (179, 'Tonga');
INSERT INTO "Countires" (id, name) VALUES (180, 'Trinidad and Tobago');
INSERT INTO "Countires" (id, name) VALUES (181, 'Tunisia');
INSERT INTO "Countires" (id, name) VALUES (182, 'Turkey');
INSERT INTO "Countires" (id, name) VALUES (183, 'Turkmenistan');
INSERT INTO "Countires" (id, name) VALUES (184, 'Tuvalu');
INSERT INTO "Countires" (id, name) VALUES (185, 'Uganda');
INSERT INTO "Countires" (id, name) VALUES (186, 'Ukraine');
INSERT INTO "Countires" (id, name) VALUES (187, 'United Arab Emirates, The');
INSERT INTO "Countires" (id, name) VALUES (188, 'United Kingdom, The');
INSERT INTO "Countires" (id, name) VALUES (189, 'Uruguay');
INSERT INTO "Countires" (id, name) VALUES (190, 'Uzbekistan');
INSERT INTO "Countires" (id, name) VALUES (191, 'Vanuatu');
INSERT INTO "Countires" (id, name) VALUES (192, 'Venezuela');
INSERT INTO "Countires" (id, name) VALUES (193, 'Vietnam');
INSERT INTO "Countires" (id, name) VALUES (194, 'Yemen');
INSERT INTO "Countires" (id, name) VALUES (195, 'Zambia');
INSERT INTO "Countires" (id, name) VALUES (196, 'Zimbabwe');
COMMIT;
